{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ include "mattermost-bridges.name" . }}
    helm.sh/chart: {{ include "mattermost-bridges.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.name }}
          servicePort: {{ .Values.service.port }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: some-cert-name
{{- end }}